### ISSUE TITLE
deployment question and uSensor app feature request

### ISSUE THREAD

**Issue by MrMontesa** [ict/ulanzi-awtrix-appdaemon#1]
Hey there,
great idea to command Ulanzi clock via AppDaemon. I'm currently commanding my clock via MQTT from some Node-Red rules, but every Ulanzi CustomApp also needs an automation to update the custom app as soon as e.g. a temp sensor changes.
So I really like you neat idea!

I have to admit, that I'm having few problems setting up the app. I already have AppDaeamon installed with another app, but somehow when adding you app, AppDaemon bails out.
Error:

```
2024-05-06 17:12:38.816496 INFO AppDaemon: Reloading Module: /config/apps/ulanzi-awtrix-appdaemon/uweather.py
2024-05-06 17:12:38.819230 INFO AppDaemon: Loading app UlanziWeather using class UlanziWeather from module uweather
2024-05-06 17:12:38.820625 INFO AppDaemon: Calling initialize() for UlanziWeather
2024-05-06 17:12:38.826438 WARNING UlanziWeather: ------------------------------------------------------------
2024-05-06 17:12:38.826688 WARNING UlanziWeather: Unexpected error in worker for App UlanziWeather:
2024-05-06 17:12:38.826879 WARNING UlanziWeather: Worker Ags: {'id': '3689c8b91a63490dab33cd39fc52a9d7', 'name': 'UlanziWeather', 'objectid': '1d8bd89b577246aa8680282a0f1cea36', 'type': 'scheduler', 'function': <bound method UlanziWeather.update_app of <uweather.UlanziWeather object at 0x7fd0591a6010>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 60, '__thread_id': 'thread-0'}}
2024-05-06 17:12:38.826998 WARNING UlanziWeather: ------------------------------------------------------------
2024-05-06 17:12:38.828063 WARNING UlanziWeather: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/apps/ulanzi-awtrix-appdaemon/uweather.py", line 144, in update_app
    self.update_app_custom()
  File "/config/apps/ulanzi-awtrix-appdaemon/uweather.py", line 99, in update_app_custom
    forecast = self.schedule_call_service()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/ulanzi-awtrix-appdaemon/uweather.py", line 88, in schedule_call_service
    self.call_service(
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 231, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 313, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/site-packages/appdaemon/adapi.py", line 1762, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/services.py", line 169, in call_service
    raise ServiceException(f"Unknown service ({namespace}/{domain}/{service}) in call_service from {name}")
appdaemon.exceptions.ServiceException: Unknown service (default/script/get_forecast_now) in call_service from UlanziWeather

2024-05-06 17:12:38.828228 WARNING UlanziWeather: ------------------------------------------------------------
2024-05-06 17:12:40.838441 INFO AppDaemon: Reading config
2024-05-06 17:12:40.843124 WARNING AppDaemon: App 'MyApp' missing 'class' or 'module' entry - ignoring
2024-05-06 17:12:40.843467 INFO AppDaemon: /config/apps/apps.yaml added or modified
```

Any idea what the culprit might be?

And secondly, I wanted to ask if you could also create a uSensor app, which can be used to display standard sensor entities?
I want to display the photovoltaic power generation, which is a simple sensor:
```
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: Total DC power
```
Or the general power consumption of the flat. Or just the temperature from a sensor without the weather overhead.
Thanks much for your help
Best Sebastian

**Comment by ict** [comment]
Hello and sorry, I just noticed this issue. Really need to set up email notifications.
Your error occurs because the weather app. needs a script in HASS to be able to work. I will document this soon.

**Comment by ict** [comment]
On second thought, the problem is already described in `uweather.py`'s documentation section. Please add the script in HASS as detailed there and restart Appdaemon. Afterwards, the app should work as expected:
https://github.com/ict/ulanzi-awtrix-appdaemon/blob/47eb6b53c4b684f54e8de2284513014bf4f45534/uweather.py#L7-40

For your other request, I'll create a separate issue.
